version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - akka
  - Antiforgery
  - appicon
  - appiconfg
  - appxmanifest
  - aspnet
  - aspnetcore
  - avalonia
  - blazor
  - efcore
  - featurization
  - maccatalyst
  - maui
  - mlnet
  - signalr
  - skyblue
ignoreWords: []
import: []
