version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - aspnet
  - aspnetcore
  - skyblue
  - appxmanifest
  - maccatalyst
  - appiconfg
  - appicon
  - maui
ignoreWords: []
import: []
