version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - appicon
  - appiconfg
  - appxmanifest
  - aspnet
  - aspnetcore
  - blazor
  - efcore
  - maccatalyst
  - maui
  - signalr
  - skyblue
ignoreWords: []
import: []
